---
apiVersion: v1
kind: Namespace
metadata:
  name: external-dns
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: external-dns
  name: external-dns
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: external-dns
rules:
- apiGroups: [""]
  resources: ["services","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["discovery.k8s.io"]
  resources: ["endpointslices"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["list", "watch"]
- apiGroups: ["externaldns.k8s.io"]
  resources: ["dnsendpoints"]
  verbs: ["get","watch","list"]
- apiGroups: ["externaldns.k8s.io"]
  resources: ["dnsendpoints/status"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: external-dns
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: external-dns
subjects:
- kind: ServiceAccount
  name: external-dns
  namespace: external-dns
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: external-dns
  name: external-dns
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: external-dns
  template:
    metadata:
      labels:
        app.kubernetes.io/name: external-dns
    spec:
      serviceAccountName: external-dns
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v0.19.0
        securityContext:
          runAsGroup: 65532
          runAsUser: 65532
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            add: [NET_BIND_SERVICE]
            drop: [ALL]
        args:
        - --source=service
        - --source=ingress
        - --source=crd
        - --managed-record-types=A
        - --managed-record-types=AAAA
        - --managed-record-types=CNAME
        - --managed-record-types=TXT
        - --txt-prefix=edns-%{record_type}-
        - --provider=webhook
      - name: external-dns-libdns-webhook
        image: ghcr.io/orbit-online/external-dns-libdns-webhook:main
        securityContext:
          runAsGroup: 65532
          runAsUser: 65532
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            add: [NET_BIND_SERVICE]
            drop: [ALL]
        args:
        - --provider.name=inwx
        - --provider.zones=example.com
        env:
        - name: INWX_USERNAME
          valueFrom:
            secretKeyRef:
              name: inwx-credentials
              key: username
        - name: INWX_PASSWORD
          valueFrom:
            secretKeyRef:
              name: inwx-credentials
              key: password
        - name: LIBDNS_PROVIDER_CONFIG
          value: |
            {
              "Username": "$(INWX_USERNAME)",
              "Password": "$(INWX_PASSWORD)"
            }
